### ISSUE TITLE
Blur effect

### ISSUE THREAD

**Issue by jassmith** [OrganonKit/Organon#5]
Hey guys, wanted to contribute my blur effect code for you to include.

[MVPDemo.zip](https://github.com/OrganonKit/Organon/files/598587/MVPDemo.zip)

**Comment by jassmith** [comment]
Sorry I didn't do this as a PR, but the contents of that demo should be enough for you to extract what is needed.

**Comment by Depechie** [comment]
Woow thanks Jason!!!
We will add it for sure... only downside you will not be listed as contributer :/

**Comment by jassmith** [comment]
Its okay ;)

**Comment by jassmith** [comment]
Just a heads up, in order to get this to work the effect has to be attached before the view is shown or you will have to resize the window to get the effect to start working. Once attached it will update correctly. I have reported the issue up to the UWP team.

**Comment by Depechie** [comment]
So we can't 'just' only add it in XAML?

**Comment by jassmith** [comment]
no you can add it in XAML, but if you add it AFTER the view is visible (say on a button press) it wont work until the window is resized

**Comment by Depechie** [comment]
ok!

**Comment by jimbobbennett** [comment]
Sweet - I guess this is the one you showed off last week, was very cool!

**Comment by Depechie** [comment]
Any way to circumvent the new IPlatformElementConfiguration<S, T> that is only in PRE forms.

**Comment by jassmith** [comment]
Replace it with a standard getter/setter. However that is going stable imminently and it would be idea to standardize on that. It is designed specifically for this kind of library.

**Comment by Depechie** [comment]
UWP blur effect added to main branch
